spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/.h2/pde/n3/m6/db
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true